name: attendance_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Quốc tế hoá (dùng bản mới, bỏ bản 0.19 cũ)
  intl: ^0.20.2

  # UI & feature deps
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0

  # Từ nhánh hai-ui
  flutter_dotenv: ^6.0.0
  http: ^1.2.0
  camera: ^0.10.6
  google_mlkit_face_detection: ^0.11.1
  provider: ^6.1.5
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
